### ISSUE TITLE
LINKS : homepage : "about" and "single-payer" link to existing site

### ISSUE THREAD

**Issue by sarmaswe** [eastbaydsa/website#129]
@wesholing, possible to update so these link to the new site?
- On homepage, under Learn More, “about East Bay DSA” links to old/existing site. (“About” in top and bottom nav link to current site.) 
- On homepage, under “Single-Payer…,” single-payer link goes to old/existing site.

**Comment by wesholing** [comment]
Yeah, fixed these too. There was an earlier issue with the previous content
editor that prevented me from making relative links on the site. Since we
have redirects in place, once the new site goes live, the absolute links
that point to the old NationBuilder URLs will still work, but I'll review
the pages before we launch to fix any of these just in case.

Wes

**Comment by kyleschmolze** [comment]
Looks like you successfully updated these to relative links, @wesholing, and they work - closing
