### ISSUE TITLE
CODE : Links : opening in new tabs inconsistently

### ISSUE THREAD

**Issue by sarmaswe** [eastbaydsa/website#159]
URLs: 
https://www.eastbaydsa.org
https://www.eastbaydsa.org/about
https://www.eastbaydsa.org/resources
https://www.eastbaydsa.org/donate
https://www.eastbaydsa.org/join

I'm outlining the inconsistent treatment of links opening in new tabs below. My suggestion would be to have all internal links open in the same tab, perhaps with the exception of PDFs; and for links to other sites to open in new tabs. 

On the homepage, links for Single Payer and Learn More open in new tabs, while other links on the page (events / top navigation) open in the existing tab. It seems all the links on the homepage are internal.

On the About page, links in copy open in a new tab, while links in the colored pages open in the existing tab. 

On the Resources page, all links are part of copy, and they all open in a new tab. 

On the Donate page, buttons open new tabs, though I think this makes sense as it's a different page.

On the Join page, the button for National DSA opens in the existing tab.  

Facebook and Twitter in the bottom nav open in the existing tab. 

This is small, but would be great to have a consistent treatment at some point. 

@dominic @wesholing @kyleschmolze @llkats 

![screen shot 2018-07-07 at 9 25 01 pm](https://user-images.githubusercontent.com/13740788/42416836-0d71515e-822e-11e8-853a-a50b61376a9d.png)

**Comment by wesholing** [comment]
I'm getting the same behavior, and it's not specific to the home page. I can't control that from the editor, so I think it's a setting built-in in the CMS.

@dominic, can you check?

**Comment by sarmaswe** [comment]
I updated the initial comment based on additional info -- @wesholing

**Comment by dominic** [comment]
Bumping this; it seems like all CMS-edited content opens in a new tab. Let's try to address this one soon cause it's weirdly annoying.

**Comment by eventualbuddha** [comment]
Based on what I've seen of the admin interface, I'm pretty sure the `target="_blank"` is just part of the HTML in the `Page#content`. They probably need to be removed manually, but I can't verify this because I don't have access to the admin site.

**Comment by eventualbuddha** [comment]
Also, the link button in the admin editor is [adding these whenever you add a link](https://github.com/quilljs/quill/blob/9a77567fe356d384074df7479c33ceac509d9351/formats/link.js#L7). Not sure how easy this would be to fix.

**Comment by kyleschmolze** [comment]
Ok, I found some issues in the Quill repo about this, and it can be done! But it is a bit annoying:

- https://github.com/quilljs/quill/issues/1139  Link without target - how to?
- [Working Codepen Example](https://codepen.io/anon/pen/GNMXZa)

I think it would be pretty easy to override all links so that we *never* use `target=_blank`, which I would advocate for. People know how to open links in a new tab if they so choose.

**Comment by tilgovi** [comment]
I've made a PR (#231) for implementing this selectively and conservatively so that only internal links (links back to the website itself) open in the same tab. This should improve navigation a little bit. Justification for limiting this to internal links can be found in the PR and the code comments.

**Comment by tnoff** [comment]
Haven't seen this in using the site so far, if we see this again we can re-open
