### ISSUE TITLE
NEW PAGE : Committees : review

### ISSUE THREAD

**Issue by sarmaswe** [eastbaydsa/website#163]
Hi, @wesholing  Will you please share info here about the new Committees page? Like where you are thinking it will live, as well as the copy and design you're thinking about? Or when you're thinking it will be ready for us to take a look?

**Comment by wesholing** [comment]
Sure thing. The page has been live since the site launched.
http://www.eastbaydsa.org/about/committees

**Comment by sarmaswe** [comment]
@kyleschmolze does the committees page cover everything you were thinking of?

http://www.eastbaydsa.org/about/committees

**Comment by kyleschmolze** [comment]
Awesome! Thanks for putting that all together, @wesholing. Some ideas:

1. In my ideal world, each committee would also have basic info on how to get involved. At a minimum, you can always just email the co-chairs, but that's an extra step many won't take (and more emails for the co-chairs to respond to). It would be great if each committee listed it's membership criteria, e.g. "Membership open to all members who've attended 2 events in the last 6 months" or "Membership closed - by appointment only." I'd also love for each committee to have a link to it's charter or the resolution that created it! Heck, the caucuses page has more info on each caucus than our committees page has info on each committee! (I assume this is because caucuses have actually been around for much longer in EBDSA.) I'd be happy to dig through meeting notes to try to pull this info together.
2. And I'd also love to list subcommittees! For me, each of these organizational units represents a way for members to get excited and get involved, so the more we can list, and the more info we have about each, the better.
3. And finally, I think it'd be great to make the committees page more accessible and promote it more. Clicking About > Committees feel like a stretch to me for people who want to get involved. I feel like an additional action item on the "Join" page (after "Attend an event"), or possibly even a "Get involved" page for people who already joined, or maybe just a link directly to the Committees page from the Homepage, could all be ways to highlight the committees. If we indeed believe that committees are "where the work gets done" then it feels like a pretty high priority place to plug people in! For me, the top priorities for the whole site would be (1) Join, (2) Events, (3) Connect with Committees and Caucuses. Would love to hear others' thoughts on that!

**Comment by sarmaswe** [comment]
@kyleschmolze I really like your feedback. Thank you for taking the time to add it. 

@wesholing what do you think about points 1 and 2? what would be the process for gathering that info?

and Kyle I hear you on number 3. Maybe tomorrow night we can get a sense of our plan for updating the landing page in general, and then see if we should bundle this change with that work, or work on it separately

**Comment by sarmaswe** [comment]
@wesholing just checking on this again. Will you please take a look at the last comment?

**Comment by wesholing** [comment]
Sorry again, still digging out from this trove of GitHub emails.

I like @kyleschmolze's suggestion about membership criteria, etc. Most committees are still formulating this information, but I'll start reaching out to them to see what they have or if they'll want to include it on the page.

In terms of content, though, if we included this info for all of these committees, this page is bound to get very long. This is another case where we'll need to consider the site's IA.
