### ISSUE TITLE
CSS framework?

### ISSUE THREAD

**Issue by dominic** [eastbaydsa/website#5]
Does anyone have a strong opinion about Bootstrap versus other CSS reset solutions? I'm fine with anything, especially if it helps us move quickly.

**Comment by nfiniteset** [comment]
I think CSS frameworks are more trouble than they're worth at this point in time. Browsers have less need of a reset these days. They're difficult to remove or upgrade because they tend to polute markup with framework-and-version-specific classes. Flex-box layout makes CSS grid frameworks obsolete. And you end up having to override these fat framework CSS files with even more CSS of your own, leading to bulky downloads and specificity conflicts. 

The only point in favor of something like Bootstrap is the default style for forms *IF* we don't plan on changing the style very much. E.g. for admin screens this can be fine and helpful.

In place of a framework, I use a couple of SCSS mixins I'll write up a little later.

**Comment by nfiniteset** [comment]
I also recommend using an auto-prefixer like [this one](https://github.com/ai/autoprefixer-rails) or similar.

**Comment by bcipriano** [comment]
How's the flex-box browser compatibility? Looks like it's not great for IE? https://caniuse.com/#feat=flexbox

Looking at that I would be a little concerned about alienating less tech-savvy folks who might be running old Windows sytems (but maybe there's an ok failure mode?)

Bootstrap is super common and might make it easier for future contributors to ramp up - I think that's another point in its favor.

Not opposed to @nfiniteset's idea, just thinking out loud.

**Comment by nfiniteset** [comment]
<img width="356" alt="screen shot 2017-10-02 at 6 21 42 pm" src="https://user-images.githubusercontent.com/178653/31106188-93cbc132-a79e-11e7-8455-2dcf0d181b09.png">

Good thought @bcipriano. 60% of our visitors are on desktop. The browser breakdown (blended mobile and desktop) is above.

Flexbox is solid in Edge, and functional with a couple of bugs to work around in IE11.

**Comment by bcipriano** [comment]
Awesome, thanks!

Good enough for me  👍

**Comment by dominic** [comment]
https://github.com/eastbaydsa/website/pull/24 has a flexbox-ed homepage layout, so i think we can close this for now. Just flexbox + SASS variables is feeling pretty good.
