### ISSUE TITLE
direct_link column on pages superfluous? how will nesting work?

### ISSUE THREAD

**Issue by kyleschmolze** [eastbaydsa/website#71]
Hey @dominic is there any purpose for the `direct_link` column on the `page` model? It seems that routing is entirely handled by the `slug` column. 

Relatedly, what's the plan for nested page routing? Obviously pages can have parents/children, which is great for displaying nav breadcrumbs / sub-pages, but is routing going to be related to parents/children as well? 

As in, if there's a page that lives at `/about/mission`, does it have the slug `mission` and parent-page `about`? Or does it have slug `/about/mission`, and the parent/child relations only tells us how to display nav/breadcrumbs?

**Comment by kyleschmolze** [comment]
(edited for clarity!)

**Comment by dominic** [comment]
`direct_link` looks like a generated attribute used for linking to a page from the admin interface. I don't see it stored in the database, so there's no data confusion.

As for pathing, I think slugs will contain the full route for now, so `/about/mission` instead of `/mission` nested under the `/about` page. The parent/child relationship can be breadcrumb only after that. I think it might be hard to track changing page paths otherwise (and hard to actually query for a page by slug without doing a bunch of DB calls).

**Comment by kyleschmolze** [comment]
Oh funky, sorry didn't notice that it was a virtual attribute! 

I think you're 100% on point about the paths. Just need to make sure people know that the slug is the *full* path. I may add some placeholder/description text.
