### ISSUE TITLE
Include date and slug in event URLs

### ISSUE THREAD

**Issue by wesholing** [eastbaydsa/website#99]
It looks like the site structures event URLs like this: `/events/8`.

Can they instead be structured like this: `/event/yyyy/mm/dd/slug`? I could revise the slugs in NationBuilder if that would help.

**Comment by kyleschmolze** [comment]
It's extremely easy to *append* to the URL with `-` characters and words, so instead of `/events/8`, it could be `/events/8--2018-05-01-may-day`, where the first 8 is still the ID of the event, and everything after the first `-` is for vanity and readability. Would this be good enough for our purposes? 

We could also do `/events/8-2018-05-01-may-day`, or any set of non-`/` characters between the `id` and the `slug`. We could even do `/events/8/2018-05-01-may-day`, although the extra '/' makes it slightly more confusing on our end for routing - but it could work.

Putting it in an extreme subfolder like `/events/yy/mm/dd/slug` seems needlessly complex, because `/` characters affect routing and we'd have to have a pretty complex routing structure for this to work properly. What happens if the date for an event changes? All previous URLs 404 now? Are all slugs unique? Keep in mind, we don't control the slugs, NationBuilder does.

**Comment by dominic** [comment]
@kyleschmolze We could also do some fun wildcard matching like:

```
match '/events/:id/*date' => 'events#show
```

Would match `/events/8/2018/05/01/may-day` (it would also match _literally anything_ since it's a wildcard), but might look nice. In terms of actual structure, I have a preference for the date formatting in `/events/8/2018-05-01/may-day`.

The biggest problem right now is that we load events by slug, and have to use their unique ID. I think the only way to do so would be to track event ID -> slug mappings in our own database so we could request the correct back-end info. 

The other caveat I see with a URL including `../2018/05/01/...` is – IMO – that it's good form for all parts of the URL to be routable if you cut it off at any particular slash. For instance:

```
Blog post: https://wordpress.org/news/2018/04/wordpress-4-9-5-security-and-maintenance-release/
April posts: https://wordpress.org/news/2018/04/
2018 posts: https://wordpress.org/news/2018/
..etc...
```

**Comment by wesholing** [comment]
@dominic Good call on the truncated URL issue. Unless there's a way for us to list all April events if the user visits eastbaydsa.org/events/2018/04, then we should avoid that.

How about this instead? `/events/slug-id`

It's better for SEO to have the keywords closer to the domain anyway, and it would keep things unique. `/events/membership-phonebank-412` versus `/events/membership-phonebank-413` and so on.

**Comment by dominic** [comment]
Love it. FWIW the "slug" in that case is basically meaningless - we will load by ID only. This also has the nice benefit of redirects working automatically if we even change a slug.
